
DELETE http://localhost:3000/assets/60154273b086611523228100 HTTP/1.1

###

GET http://localhost:3000/assets HTTP/1.1


###

POST http://localhost:3000/assets HTTP/1.1
content-type: application/json

{
    "catalogItemName": "Pro 5G XL",
    "catalogItemId": "109222",
    "instanceId": "0400697545",
    "owner": "Aku Ankka",
    "user": "Iines Ankka",
    "bu": "Finland",
    "params": "ASD, ASD, ASD, ASD"
}
###

POST http://localhost:3000/assets HTTP/1.1
content-type: application/json

{
    "catalogItemName": "Pro 5G XL",
    "catalogItemId": "109222",
    "instanceId": "0400697545",
    "owner": "Roope Setä",
    "user": "Yaroslav Mulkku",
    "bu": "Finland",
    "params": "ASD, ASD, ASD, ASD"
}

###

POST http://localhost:3000/assets HTTP/1.1
content-type: application/json

{
    "catalogItemName": "Liikkuva 4G M",
    "catalogItemId": "109333",
    "instanceId": "0400697544",
    "owner": "Kimi Räikkönen",
    "user": "Ayrton Senna",
    "bu": "Finland",
    "params": "ASD, ASD, ASD, ASD"
}

###
