
DELETE http://localhost:3002/order/60155b0b534cc5165e6ea1d0 HTTP/1.1

###

GET http://localhost:3002/order HTTP/1.1

###

POST http://localhost:3002/order HTTP/1.1
content-type: application/json

{
    "catalogItemId": "109333",
    "orderStatus": 2,
    "costCenter": "1234567890",
    "customerId": "A2M123451234A",
    "user": "Hessu Svensson",
    "bu": "Sweden",
    "params": ":D"
}
###

POST http://localhost:3002/catalog HTTP/1.1
content-type: application/json

{
    "catalogItemName": "Liikkuva 4G M",
    "category": "Mobile connectivity",
    "catalogItemId": "109333",
    "description": "Liittymäasiat kunnossa ihan ok",
    "bu": "Sweden",
    "price": 3,
    "discount": 0,
    "imgUrl": "https://www.telia.fi/dam/jcr:9da943d7-8b60-4d9f-8ccd-598d25f4f69d/Minun-Telia-split-grey-1440x800.jpg",
    "params": "WTF, ASD, ASD, ASD"
}

###